# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tidytuesday006',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/tidytuesday006',
                'lib_path': 'tidytuesday006'},
  'syms': {'tidytuesday006.core': {'tidytuesday006.core.foo': ('core.html#foo', 'tidytuesday006/core.py')}}}
